# Generated by Django 3.2.22 on 2023-12-04 15:37

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulltextsearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulltext',
            name='svf',
            field=django.contrib.postgres.search.SearchVectorField(default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='fulltext',
            index=django.contrib.postgres.indexes.GinIndex(fields=['svf'], name='fulltextsea_svf_a950a3_gin'),
        ),
        migrations.RunSQL(
            "UPDATE fulltextsearch_fulltext SET svf=to_tsvector(content);"
        ),
    ]
